services:
  - type: web
    name: whale-wars-ws
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18.0.0 